/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuame_rootgenius_sdk_JniHelper_Data */

#ifndef _Included_com_shuame_rootgenius_sdk_JniHelper_Data
#define _Included_com_shuame_rootgenius_sdk_JniHelper_Data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
