/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuame_rootgenius_sdk_JniHelper */

#ifndef _Included_com_shuame_rootgenius_sdk_JniHelper
#define _Included_com_shuame_rootgenius_sdk_JniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shuame_rootgenius_sdk_JniHelper
 * Method:    rgMain
 * Signature: (Lcom/shuame/rootgenius/sdk/JniHelper/Data;)I
 */
JNIEXPORT jint JNICALL Java_com_shuame_rootgenius_sdk_JniHelper_rgMain
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_shuame_rootgenius_sdk_JniHelper
 * Method:    verify
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_shuame_rootgenius_sdk_JniHelper_verify
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
